# Dependabot configuration file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/discordbot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/dllgenerator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/game-ci"
    schedule:
      interval: "weekly"
